** 1. CUSTOMERS **
CREATE TABLE CUSTOMERS (
CustomerID INT NOT NULL PRIMARY KEY,
CustomerName NVARCHAR(255) NOT NULL,
CustomerDOB DATE,
CustomerEmail NVARCHAR(255) NOT NULL,
CustomerPhone NVARCHAR(50) NOT NULL,
CustomerAddress NTEXT NOT NULL
) 

** 2. PETS **
CREATE TABLE PETS (
PetID INT NOT NULL PRIMARY KEY,
CustomerID INT NOT NULL,
Species NVARCHAR(50) NOT NULL,
Weight FLOAT NOT NULL,
PetDOB DATE NOT NULL,
MedicalNote NTEXT,
CONSTRAINT FK_PETS_CUSTOMER FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID)
) 

** 3. EMPLOYEES **
CREATE TABLE EMPLOYEES (
EmployeeID INT NOT NULL PRIMARY KEY,
EmployeeName NVARCHAR(255) NOT NULL,
EmployeeDOB DATE,
EmployeeEmail NVARCHAR(255) NOT NULL,
EmployeePhone NVARCHAR(255) NOT NULL,
Position NVARCHAR(255) NOT NULL
)

** 4. SERVICES **
CREATE TABLE SERVICES(
ServiceID INT NOT NULL PRIMARY KEY,
Category NVARCHAR(255) NOT NULL,
Description NTEXT,
Price DECIMAL(10, 2) NOT NULL,
Target_animal NVARCHAR(255) NOT NULL
)

** 5. BOOKING_FORM **
CREATE TABLE BOOKING_FORM (
BookingID INT NOT NULL PRIMARY KEY,
CustomerID INT NOT NULL,
PetID INT NOT NULL,
BookingDate DATE NOT NULL,
AppointmentDateTime DATETIME NOT NULL,
CONSTRAINT FK_BOOKINGFORM_CUSTOMER FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID),
CONSTRAINT FK_BOOKINGFORM_PET FOREIGN KEY (PetID) REFERENCES PETS (PetID)
)

** 6. FEEDBACK **
CREATE TABLE FEEDBACK (
FeedbackID INT NOT NULL PRIMARY KEY,
CustomerID INT NOT NULL,
Comment NTEXT,
FeedbackDate DATE NOT NULL,
CONSTRAINT FK_FEEDBACK_CUSTOMER FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID)
)
  
** 7. INVOICE **
CREATE TABLE INVOICE (
InvoiceID INT NOT NULL PRIMARY KEY,
InvoiceDate DATETIME NOT NULL,
Amount DECIMAL(10,2) NOT NULL,
TaxAmount DECIMAL(10,2),
TotalAmount DECIMAL(10,2) NOT NULL,
InvoiceNote TEXT,
Status VARCHAR(255) NOT NULL,
CreatedAt DATETIME NOT NULL
)

** 8. PAYMENTS **
CREATE TABLE PAYMENT (
PaymentID INT NOT NULL PRIMARY KEY,
InvoiceID INT NOT NULL UNIQUE,
PaymentDateTime DATETIME NOT NULL,
Amount MONEY NOT NULL,
Bill IMAGE,
CONSTRAINT FK_PAYMENT_INVOICE FOREIGN KEY (InvoiceID) REFERENCES INVOICE(InvoiceID)
)

** 9 .BOOKING DETAILS **
CREATE TABLE BOOKING_DETAILS (
BookingID INT NOT NULL,
ServiceID INT NOT NULL,
ServiceStatus VARCHAR(255) NOT NULL,
ServicePrice DECIMAL(10, 2) NOT NULL,
Quantity INT NOT NULL,
PromotionID INT,
Discount DECIMAL(10, 2),
Total_Amount DECIMAL(10, 2) NOT NULL,
CONSTRAINT PK_BOOKING_DETAILS PRIMARY KEY (BookingID, ServiceID),
CONSTRAINT FK_BOOKINGDETAILS_BOOKING FOREIGN KEY (BookingID) REFERENCES BOOKING_FORM(BookingID),
CONSTRAINT FK_BOOKINGDETAILS_SERVICE FOREIGN KEY (ServiceID) REFERENCES SERVICES(ServiceID)
)

** 10. PRECHECK **
CREATE TABLE PRECHECK (
PrecheckID INT NOT NULL PRIMARY KEY,
PetID INT NOT NULL,
GeneralCondition NVARCHAR(255) NOT NULL,
SkinCondition TEXT,
BehaviorNotes TEXT,
CreatedAt DATETIME NOT NULL,
CONSTRAINT FK_PRECHECK_PET FOREIGN KEY (PetID) REFERENCES PETS(PetID)
)

** 11. PERFORMANCE **
CREATE TABLE PERFORMANCE (
PerformanceID INT NOT NULL PRIMARY KEY,
StartTime DATETIME NOT NULL,
EndTime DATETIME NOT NULL,
CreatedAt DATETIME NOT NULL,
CONSTRAINT FK_PERFORMANCE_BOOKING FOREIGN KEY (PerformanceID) REFERENCES BOOKING_FORM(BookingID)
)


** 12. PERFORMANCE_DETAIL **
CREATE TABLE PERFORMANCE_DETAIL (
PerformanceID INT NOT NULL,
InvoiceID INT NOT NULL,
Status VARCHAR(50) NOT NULL,
Result NVARCHAR(255),
Notes TEXT,
CONSTRAINT PK_PERFORMANCE_DETAIL PRIMARY KEY (PerformanceID,InvoiceID), 
CONSTRAINT FK_PD_PERFORMANCE FOREIGN KEY (PerformanceID) REFERENCES PERFORMANCE(PerformanceID),
CONSTRAINT FK_PD_INVOICE FOREIGN KEY (InvoiceID) REFERENCES INVOICE(InvoiceID)
)

** 13. PRECHECK_EMPLOYEE **
CREATE TABLE PRECHECK_EMPLOYEE (
    PrecheckID INT NOT NULL,
    EmployeeID INT NOT NULL,
    Role NVARCHAR(255) NOT NULL,
    CheckTime DATETIME NOT NULL,
    CONSTRAINT PK_PRECHECK_EMPLOYEE PRIMARY KEY (PrecheckID, EmployeeID),
    CONSTRAINT FK_PE_PRECHECK FOREIGN KEY (PrecheckID) REFERENCES PRECHECK(PrecheckID),
    CONSTRAINT FK_PE_EMPLOYEE FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEES(EmployeeID)
)

